name: 'Deploy Stellaris mod update action'
description: 'Run Python script to bump version numbers, set supported Stellaris version, and create a Github release.'
author: 'Aerolfos'
inputs:
  versionType:
    description: 'Version type to bump, follows semantic versioning'
    required: true
    default: 'Patch'
    type: choice
    options:
    - 'Major'
    - 'Minor'
    - 'Patch'
  versionStellaris:
    description: 'Stellaris version to support'
    required: true
    type: string
  useChangelog:
    description: |
          Fill in changelog for release?

          Expects a CHANGELOG.md file in target repo
    required: true
    type: boolean

runs:
  using: 'composite'
  steps:
    - name: 'Run main script'
      run: python main.py "${{ inputs.versionType }}" "${{ inputs.versionStellaris }}" "${{ inputs.useChangelog }}"
      shell: bash
