# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: "Stellaris Mod Deploy Tool"
site_url: https://Aerolfos.github.io/stellaris_mod_deploy_action/
theme:
  name: readthedocs

# base64 encoded starbase icon (used as logo for docs)
# &logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEiSURBVDhPpdNNK0RRHMfxGZOnhYesKa9AsVBT9haysPESvArlfXgDytaaYoOalUhZEEnJRjYYruv7vd0z7p17bk351adbp//5n4c500zTtPGfxBrMYgVtLDhALnCOEzw60IsNcqPYRgd1ucQOxpDNC5PnsI9BcwDnZA2WcI9Bk+TfZ6wNcYoNfOAB7/hCXbwwa7wH56y7gxb8juAYXdTF1U8R7qDlDhKYb8xgGF0H+vID6ydgrUkcCLFgF3sITYv5xB0OERqUfsZgHK/ozxPCcXuKOwhxdS/LFb1Qj+OKjrvLUmINLPLlLeIFm7jGKiqJNWiig1vY6ApHuEHl3ZfOk/P/MYkpnGEZsbpMbAeu8oYtzMOHNo14Yl0L2qjc/J+08QsSm7YScC+/WAAAAABJRU5ErkJggg==
