# This is an example workflow, which sets up and runs python and the supporting stuff needed

name: Python application

on:
  workflow_dispatch
  
permissions:
  contents: write

jobs:
  updateStellarisMod:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repo
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Run action
      run: python main.py
