# This is a reusable workflow, which sets up and runs python and the supporting stuff needed
# Call from another workflow, which will only need inputs

name: 'Trigger reusable workflow to deploy Stellaris mod update'
# Will run Python script to bump version numbers, set supported Stellaris version, and create a Github release.
run-name: "${{ github.actor }} triggered a ${{ inputs.versionType }} update"

on:
  # used to avoid having to retype all this, call from another (simple) workflow
  # sadly you do need to copy the inputs everywhere
  workflow_call:
    inputs:
      versionType:
        description: 'Version type to bump, follows semantic versioning'
        required: true
        default: 'Patch'
        type: string
      versionStellaris:
        description: 'Stellaris version to support'
        required: true
        type: string
      useChangelog:
        description: |
          Fill in changelog for release?

          Expects a CHANGELOG.md file in target repo
        required: true
        type: boolean
  
  # for testing can run this workflow directly
  # this won't work because it lacks files to operate on, it's really just to see the inputs displayed and have a reference for them
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Version type to bump, follows semantic versioning'
        required: true
        default: 'Patch'
        type: choice
        options:
        - 'Major'
        - 'Minor'
        - 'Patch'
      versionStellaris:
        description: 'Stellaris version to support'
        required: true
        type: string
      useChangelog:
        description: |
          Fill in changelog for release?

          Expects a CHANGELOG.md file in target repo
        required: true
        type: boolean
      
permissions:
  contents: write

jobs:
  updateStellarisMod:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the mod repo
      uses: actions/checkout@v4
      with:
        # actions/checkout does not allow cloning to a folder above the default working folder, so to separate from tools place in this folder
        # the path names become very long but needs checkout to fix their shit to change
        path: ${{ github.event.repository.name }}
    
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: aerolfos/stellaris_mod_deploy_action
        # actions/checkout does not allow cloning to a folder above the default working folder, so to separate from mod files place in this folder
        path: stellaris_mod_deploy_action
        # avoid needlessly cloning the graphic assets, want root folder with script files and extra scripts in methods though
        sparse-checkout: |
          .github
          methods
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # TODO
    - name: Test print file structure
      run: |
        cd ../
        tree
    
    # action expects to be run from a directory that's alongside the relevant mod repo, see tools step above
    - name: Run associated Python action
      id: main_python_action
      uses: aerolfos/stellaris_mod_deploy_action@main
      with: 
        versionType: ${{ inputs.versionType }}
        versionStellaris: ${{ inputs.versionStellaris }}
        useChangelog: ${{ inputs.useChangelog }}

    - name: 'Test print release title'
      id: test_release_title_print
      working-directory: ${{ github.event.repository.name }}
      run: printf '%s\n' "$MOD_RELEASE_TITLE"
      shell: bash
    
    - name: 'Commit and push changes from Python script'
      id: main_commit_push
      working-directory: ${{ github.event.repository.name }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Generate release for $MOD_RELEASE_TITLE"
        git push
      shell: bash

    - name: 'Copy descriptor, and make a zip with mod files for release'
      id: main_zip_for_release
      working-directory: ${{ github.event.repository.name }}
      # copy descriptor file from mod files up one folder, renamed to same as mod folder
      # this matches what the user needs to drop in Stellaris/mod - zip this for release
      run: |
        cp ${{ github.event.repository.name }}/$MOD_DESCRIPTOR_FILE ${{ github.event.repository.name }}.mod
        zip -r ${MOD_RELEASE_ZIP_FILE} ${{ github.event.repository.name }} ${{ github.event.repository.name }}.mod
      shell: bash

    - name: 'Create a release object, attach zip of mod files + descriptor'
      id: main_gh_release
      working-directory: ${{ github.event.repository.name }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create $MOD_RELEASE_TAG $MOD_RELEASE_ZIP_FILE --title "$MOD_RELEASE_TITLE" --notes-file $MOD_RELEASENOTES_FILE
      shell: bash

